/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class EnumRows {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EnumRows(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnumRows obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

   protected void finalize() {
   }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_EnumRows(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Close() {
    FGDBJNIWrapperJNI.EnumRows_Close(swigCPtr, this);
  }

  public int GetFieldInformation(FieldInfo fieldInfo) {
    return FGDBJNIWrapperJNI.EnumRows_GetFieldInformation(swigCPtr, this, FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public EnumRows() {
    this(FGDBJNIWrapperJNI.new_EnumRows(), true);
  }

  public Row next() {
    long cPtr = FGDBJNIWrapperJNI.EnumRows_next(swigCPtr, this);
    return (cPtr == 0) ? null : new Row(cPtr, true);
  }

  public VectorOfFieldDef getFields() {
    return new VectorOfFieldDef(FGDBJNIWrapperJNI.EnumRows_getFields(swigCPtr, this), true);
  }

}
