/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class Envelope {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Envelope(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Envelope obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_Envelope(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean IsEmpty() {
    return FGDBJNIWrapperJNI.Envelope_IsEmpty(swigCPtr, this);
  }

  public void SetEmpty() {
    FGDBJNIWrapperJNI.Envelope_SetEmpty(swigCPtr, this);
  }

  public Envelope() {
    this(FGDBJNIWrapperJNI.new_Envelope__SWIG_0(), true);
  }

  public Envelope(double xmin, double xmax, double ymin, double ymax) {
    this(FGDBJNIWrapperJNI.new_Envelope__SWIG_1(xmin, xmax, ymin, ymax), true);
  }

  public void setXMin(double value) {
    FGDBJNIWrapperJNI.Envelope_xMin_set(swigCPtr, this, value);
  }

  public double getXMin() {
    return FGDBJNIWrapperJNI.Envelope_xMin_get(swigCPtr, this);
  }

  public void setYMin(double value) {
    FGDBJNIWrapperJNI.Envelope_yMin_set(swigCPtr, this, value);
  }

  public double getYMin() {
    return FGDBJNIWrapperJNI.Envelope_yMin_get(swigCPtr, this);
  }

  public void setXMax(double value) {
    FGDBJNIWrapperJNI.Envelope_xMax_set(swigCPtr, this, value);
  }

  public double getXMax() {
    return FGDBJNIWrapperJNI.Envelope_xMax_get(swigCPtr, this);
  }

  public void setYMax(double value) {
    FGDBJNIWrapperJNI.Envelope_yMax_set(swigCPtr, this, value);
  }

  public double getYMax() {
    return FGDBJNIWrapperJNI.Envelope_yMax_get(swigCPtr, this);
  }

  public void setZMin(double value) {
    FGDBJNIWrapperJNI.Envelope_zMin_set(swigCPtr, this, value);
  }

  public double getZMin() {
    return FGDBJNIWrapperJNI.Envelope_zMin_get(swigCPtr, this);
  }

  public void setZMax(double value) {
    FGDBJNIWrapperJNI.Envelope_zMax_set(swigCPtr, this, value);
  }

  public double getZMax() {
    return FGDBJNIWrapperJNI.Envelope_zMax_get(swigCPtr, this);
  }

}
