/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class FieldDef {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FieldDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_FieldDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FieldDef() {
    this(FGDBJNIWrapperJNI.new_FieldDef(), true);
  }

  public int SetName(String name) {
    return FGDBJNIWrapperJNI.FieldDef_SetName(swigCPtr, this, name);
  }

  public int SetAlias(String alias) {
    return FGDBJNIWrapperJNI.FieldDef_SetAlias(swigCPtr, this, alias);
  }

  public int SetType(FieldType type) {
    return FGDBJNIWrapperJNI.FieldDef_SetType(swigCPtr, this, type.swigValue());
  }

  public int SetLength(int length) {
    return FGDBJNIWrapperJNI.FieldDef_SetLength(swigCPtr, this, length);
  }

  public int SetIsNullable(boolean isNullable) {
    return FGDBJNIWrapperJNI.FieldDef_SetIsNullable(swigCPtr, this, isNullable);
  }

  public int GetGeometryDef(GeometryDef geometryDef) {
    return FGDBJNIWrapperJNI.FieldDef_GetGeometryDef(swigCPtr, this, GeometryDef.getCPtr(geometryDef), geometryDef);
  }

  public int SetGeometryDef(GeometryDef geometryDef) {
    return FGDBJNIWrapperJNI.FieldDef_SetGeometryDef(swigCPtr, this, GeometryDef.getCPtr(geometryDef), geometryDef);
  }

  public String getAlias() {
    return FGDBJNIWrapperJNI.FieldDef_getAlias(swigCPtr, this);
  }

  public String getName() {
    return FGDBJNIWrapperJNI.FieldDef_getName(swigCPtr, this);
  }

  public boolean isNullable() {
    return FGDBJNIWrapperJNI.FieldDef_isNullable(swigCPtr, this);
  }

  public int getLength() {
    return FGDBJNIWrapperJNI.FieldDef_getLength(swigCPtr, this);
  }

  public FieldType getType() {
    return FieldType.swigToEnum(FGDBJNIWrapperJNI.FieldDef_getType(swigCPtr, this));
  }

}
