/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class GeometryDef {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GeometryDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeometryDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_GeometryDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeometryDef() {
    this(FGDBJNIWrapperJNI.new_GeometryDef(), true);
  }

  public int SetGeometryType(GeometryType geometryType) {
    return FGDBJNIWrapperJNI.GeometryDef_SetGeometryType(swigCPtr, this, geometryType.swigValue());
  }

  public int SetHasZ(boolean hasZ) {
    return FGDBJNIWrapperJNI.GeometryDef_SetHasZ(swigCPtr, this, hasZ);
  }

  public int SetHasM(boolean hasM) {
    return FGDBJNIWrapperJNI.GeometryDef_SetHasM(swigCPtr, this, hasM);
  }

  public int GetSpatialReference(SpatialReference spatialReference) {
    return FGDBJNIWrapperJNI.GeometryDef_GetSpatialReference(swigCPtr, this, SpatialReference.getCPtr(spatialReference), spatialReference);
  }

  public int SetSpatialReference(SpatialReference spatialReference) {
    return FGDBJNIWrapperJNI.GeometryDef_SetSpatialReference(swigCPtr, this, SpatialReference.getCPtr(spatialReference), spatialReference);
  }

  public boolean hasM() {
    return FGDBJNIWrapperJNI.GeometryDef_hasM(swigCPtr, this);
  }

  public boolean hasZ() {
    return FGDBJNIWrapperJNI.GeometryDef_hasZ(swigCPtr, this);
  }

  public GeometryType getGeometryType() {
    return GeometryType.swigToEnum(FGDBJNIWrapperJNI.GeometryDef_getGeometryType(swigCPtr, this));
  }

}
