/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class Guid {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Guid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Guid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_Guid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Guid() {
    this(FGDBJNIWrapperJNI.new_Guid(), true);
  }

  public void SetNull() {
    FGDBJNIWrapperJNI.Guid_SetNull(swigCPtr, this);
  }

  public void Create() {
    FGDBJNIWrapperJNI.Guid_Create(swigCPtr, this);
  }

  public int FromString(String guidString) {
    return FGDBJNIWrapperJNI.Guid_FromString(swigCPtr, this, guidString);
  }

  public boolean equal(Guid other) {
    return FGDBJNIWrapperJNI.Guid_equal(swigCPtr, this, Guid.getCPtr(other), other);
  }

  public boolean notEqual(Guid other) {
    return FGDBJNIWrapperJNI.Guid_notEqual(swigCPtr, this, Guid.getCPtr(other), other);
  }

  public String toString() {
    return FGDBJNIWrapperJNI.Guid_toString(swigCPtr, this);
  }

}
