/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class Table {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Table(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Table obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

   protected void finalize() {
   }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_Table(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int SetDocumentation(String documentation) {
    return FGDBJNIWrapperJNI.Table_SetDocumentation(swigCPtr, this, documentation);
  }

  public int GetFieldInformation(FieldInfo fieldInfo) {
    return FGDBJNIWrapperJNI.Table_GetFieldInformation(swigCPtr, this, FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public int AddField(String fieldDef) {
    return FGDBJNIWrapperJNI.Table_AddField__SWIG_0(swigCPtr, this, fieldDef);
  }

  public int AddField(FieldDef fieldDef) {
    return FGDBJNIWrapperJNI.Table_AddField__SWIG_1(swigCPtr, this, FieldDef.getCPtr(fieldDef), fieldDef);
  }

  public int AlterField(String fieldDef) {
    return FGDBJNIWrapperJNI.Table_AlterField(swigCPtr, this, fieldDef);
  }

  public int DeleteField(String fieldName) {
    return FGDBJNIWrapperJNI.Table_DeleteField(swigCPtr, this, fieldName);
  }

  public int AddIndex(String indexDef) {
    return FGDBJNIWrapperJNI.Table_AddIndex__SWIG_0(swigCPtr, this, indexDef);
  }

  public int AddIndex(IndexDef indexDef) {
    return FGDBJNIWrapperJNI.Table_AddIndex__SWIG_1(swigCPtr, this, IndexDef.getCPtr(indexDef), indexDef);
  }

  public int DeleteIndex(String indexName) {
    return FGDBJNIWrapperJNI.Table_DeleteIndex(swigCPtr, this, indexName);
  }

  public int CreateSubtype(String subtypeDef) {
    return FGDBJNIWrapperJNI.Table_CreateSubtype(swigCPtr, this, subtypeDef);
  }

  public int AlterSubtype(String subtypeDef) {
    return FGDBJNIWrapperJNI.Table_AlterSubtype(swigCPtr, this, subtypeDef);
  }

  public int DeleteSubtype(String subtypeName) {
    return FGDBJNIWrapperJNI.Table_DeleteSubtype(swigCPtr, this, subtypeName);
  }

  public int EnableSubtypes(String subtypeFieldName, String subtypeDef) {
    return FGDBJNIWrapperJNI.Table_EnableSubtypes(swigCPtr, this, subtypeFieldName, subtypeDef);
  }

  public int SetDefaultSubtypeCode(int defaultCode) {
    return FGDBJNIWrapperJNI.Table_SetDefaultSubtypeCode(swigCPtr, this, defaultCode);
  }

  public int DisableSubtypes() {
    return FGDBJNIWrapperJNI.Table_DisableSubtypes(swigCPtr, this);
  }

  public int GetExtent(Envelope extent) {
    return FGDBJNIWrapperJNI.Table_GetExtent(swigCPtr, this, Envelope.getCPtr(extent), extent);
  }

  public Table() {
    this(FGDBJNIWrapperJNI.new_Table(), true);
  }

  public boolean isEditable() {
    return FGDBJNIWrapperJNI.Table_isEditable(swigCPtr, this);
  }

  public String getDefinition() {
    return FGDBJNIWrapperJNI.Table_getDefinition(swigCPtr, this);
  }

  public String getDocumentation() {
    return FGDBJNIWrapperJNI.Table_getDocumentation(swigCPtr, this);
  }

  public int getRowCount() {
    return FGDBJNIWrapperJNI.Table_getRowCount(swigCPtr, this);
  }

  public int getDefaultSubtypeCode() {
    return FGDBJNIWrapperJNI.Table_getDefaultSubtypeCode(swigCPtr, this);
  }

  public VectorOfString getIndexes() {
    return new VectorOfString(FGDBJNIWrapperJNI.Table_getIndexes(swigCPtr, this), true);
  }

  public Row createRowObject() {
    long cPtr = FGDBJNIWrapperJNI.Table_createRowObject(swigCPtr, this);
    return (cPtr == 0) ? null : new Row(cPtr, true);
  }

  public void insertRow(Row row) {
    FGDBJNIWrapperJNI.Table_insertRow(swigCPtr, this, Row.getCPtr(row), row);
  }

  public void updateRow(Row row) {
    FGDBJNIWrapperJNI.Table_updateRow(swigCPtr, this, Row.getCPtr(row), row);
  }

  public void deleteRow(Row row) {
    FGDBJNIWrapperJNI.Table_deleteRow(swigCPtr, this, Row.getCPtr(row), row);
  }

  public EnumRows search(String subfields, String whereClause, Envelope envelope, boolean recycling) {
    long cPtr = FGDBJNIWrapperJNI.Table_search__SWIG_0(swigCPtr, this, subfields, whereClause, Envelope.getCPtr(envelope), envelope, recycling);
    return (cPtr == 0) ? null : new EnumRows(cPtr, true);
  }

  public EnumRows search(String subfields, String whereClause, boolean recycling) {
    long cPtr = FGDBJNIWrapperJNI.Table_search__SWIG_1(swigCPtr, this, subfields, whereClause, recycling);
    return (cPtr == 0) ? null : new EnumRows(cPtr, true);
  }

  public void setLoadOnlyMode(boolean loadOnly) {
    FGDBJNIWrapperJNI.Table_setLoadOnlyMode(swigCPtr, this, loadOnly);
  }

  public void setWriteLock() {
    FGDBJNIWrapperJNI.Table_setWriteLock(swigCPtr, this);
  }

  public void freeWriteLock() {
    FGDBJNIWrapperJNI.Table_freeWriteLock(swigCPtr, this);
  }

  public VectorOfFieldDef getFields() {
    return new VectorOfFieldDef(FGDBJNIWrapperJNI.Table_getFields(swigCPtr, this), true);
  }

}
