//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * ESRI Attribute set constraint object.
 *
 * <p>Java class for CodedValueDomain complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CodedValueDomain">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.esri.com/schemas/ArcGIS/10.1}Domain">
 *       &lt;sequence>
 *         &lt;element name="CodedValues" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfCodedValue"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "CodedValueDomain",
  propOrder = {"codedValues"}
)
public class CodedValueDomain extends Domain {

  @XmlElement(name = "CodedValues", required = true)
  protected ArrayOfCodedValue codedValues;

  /**
   * Gets the value of the codedValues property.
   *
   * @return possible object is {@link ArrayOfCodedValue }
   */
  public ArrayOfCodedValue getCodedValues() {
    return codedValues;
  }

  /**
   * Sets the value of the codedValues property.
   *
   * @param value allowed object is {@link ArrayOfCodedValue }
   */
  public void setCodedValues(ArrayOfCodedValue value) {
    this.codedValues = value;
  }
}
