//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for DataElement complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChildrenExpanded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FullPropsRetrieved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MetadataRetrieved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Metadata" type="{http://www.esri.com/schemas/ArcGIS/10.1}XmlPropertySet" minOccurs="0"/>
 *         &lt;element name="Children" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfDataElement" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "DataElement",
  propOrder = {
    "catalogPath",
    "name",
    "childrenExpanded",
    "fullPropsRetrieved",
    "metadataRetrieved",
    "metadata",
    "children"
  }
)
@XmlSeeAlso({DEDataset.class})
public abstract class DataElement {

  @XmlElement(name = "CatalogPath", required = true)
  protected String catalogPath;

  @XmlElement(name = "Name", required = true)
  protected String name;

  @XmlElement(name = "ChildrenExpanded")
  protected Boolean childrenExpanded;

  @XmlElement(name = "FullPropsRetrieved")
  protected Boolean fullPropsRetrieved;

  @XmlElement(name = "MetadataRetrieved")
  protected Boolean metadataRetrieved;

  @XmlElementRef(name = "Metadata", type = JAXBElement.class, required = false)
  protected JAXBElement<XmlPropertySet> metadata;

  @XmlElement(name = "Children")
  protected ArrayOfDataElement children;

  /**
   * Gets the value of the catalogPath property.
   *
   * @return possible object is {@link String }
   */
  public String getCatalogPath() {
    return catalogPath;
  }

  /**
   * Sets the value of the catalogPath property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCatalogPath(String value) {
    this.catalogPath = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the childrenExpanded property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isChildrenExpanded() {
    return childrenExpanded;
  }

  /**
   * Sets the value of the childrenExpanded property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setChildrenExpanded(Boolean value) {
    this.childrenExpanded = value;
  }

  /**
   * Gets the value of the fullPropsRetrieved property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isFullPropsRetrieved() {
    return fullPropsRetrieved;
  }

  /**
   * Sets the value of the fullPropsRetrieved property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setFullPropsRetrieved(Boolean value) {
    this.fullPropsRetrieved = value;
  }

  /**
   * Gets the value of the metadataRetrieved property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isMetadataRetrieved() {
    return metadataRetrieved;
  }

  /**
   * Sets the value of the metadataRetrieved property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setMetadataRetrieved(Boolean value) {
    this.metadataRetrieved = value;
  }

  /**
   * Gets the value of the metadata property.
   *
   * @return possible object is {@link JAXBElement }{@code <}{@link XmlPropertySet }{@code >}
   */
  public JAXBElement<XmlPropertySet> getMetadata() {
    return metadata;
  }

  /**
   * Sets the value of the metadata property.
   *
   * @param value allowed object is {@link JAXBElement }{@code <}{@link XmlPropertySet }{@code >}
   */
  public void setMetadata(JAXBElement<XmlPropertySet> value) {
    this.metadata = value;
  }

  /**
   * Gets the value of the children property.
   *
   * @return possible object is {@link ArrayOfDataElement }
   */
  public ArrayOfDataElement getChildren() {
    return children;
  }

  /**
   * Sets the value of the children property.
   *
   * @param value allowed object is {@link ArrayOfDataElement }
   */
  public void setChildren(ArrayOfDataElement value) {
    this.children = value;
  }
}
