//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.eclipse.persistence.oxm.annotations.XmlMarshalNullRepresentation;
import org.eclipse.persistence.oxm.annotations.XmlNullPolicy;

/**
 * Table Data Element object.
 *
 * <p>Java class for DETable complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DETable">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.esri.com/schemas/ArcGIS/10.1}DEDataset">
 *       &lt;sequence>
 *         &lt;element name="HasOID" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="OIDFieldName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fields" type="{http://www.esri.com/schemas/ArcGIS/10.1}Fields"/>
 *         &lt;element name="Indexes" type="{http://www.esri.com/schemas/ArcGIS/10.1}Indexes"/>
 *         &lt;element name="CLSID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EXTCLSID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RelationshipClassNames" type="{http://www.esri.com/schemas/ArcGIS/10.1}Names" minOccurs="0"/>
 *         &lt;element name="AliasName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HasGlobalID" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="GlobalIDFieldName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RasterFieldName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExtensionProperties" type="{http://www.esri.com/schemas/ArcGIS/10.1}PropertySet" minOccurs="0"/>
 *         &lt;element name="SubtypeFieldName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DefaultSubtypeCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Subtypes" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfSubtype" minOccurs="0"/>
 *         &lt;element name="ControllerMemberships" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfControllerMembership" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "DETable",
  propOrder = {
    "hasOID",
    "oidFieldName",
    "fields",
    "indexes",
    "clsid",
    "extclsid",
    "relationshipClassNames",
    "aliasName",
    "modelName",
    "hasGlobalID",
    "globalIDFieldName",
    "rasterFieldName",
    "extensionProperties",
    "subtypeFieldName",
    "defaultSubtypeCode",
    "subtypes",
    "controllerMemberships"
  }
)
@XmlSeeAlso({DEFeatureClass.class})
public class DETable extends DEDataset {

  @XmlElement(name = "HasOID")
  protected boolean hasOID = true;

  @XmlElement(name = "OIDFieldName")
  protected String oidFieldName;

  @XmlElement(name = "Fields", required = true)
  protected Fields fields;

  @XmlElement(name = "Indexes", required = true)
  protected Indexes indexes;

  @XmlElement(name = "CLSID")
  protected String clsid = "{52353152-891A-11D0-BEC6-00805F7C4268}";

  @XmlElement(name = "EXTCLSID")
  @XmlNullPolicy(
    emptyNodeRepresentsNull = true,
    nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE
  )
  protected String extclsid;

  @XmlElement(name = "RelationshipClassNames")
  protected Names relationshipClassNames;

  @XmlElement(name = "AliasName")
  protected String aliasName;

  @XmlElement(name = "ModelName")
  protected String modelName;

  @XmlElement(name = "HasGlobalID")
  protected Boolean hasGlobalID = false;

  @XmlElement(name = "GlobalIDFieldName")
  @XmlNullPolicy(
    emptyNodeRepresentsNull = true,
    nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE
  )
  protected String globalIDFieldName;

  @XmlElement(name = "RasterFieldName", required = true)
  @XmlNullPolicy(
    emptyNodeRepresentsNull = true,
    nullRepresentationForXml = XmlMarshalNullRepresentation.EMPTY_NODE
  )
  protected String rasterFieldName;

  @XmlElement(name = "ExtensionProperties")
  protected PropertySet extensionProperties = new PropertySet();

  @XmlElement(name = "SubtypeFieldName")
  protected String subtypeFieldName;

  @XmlElement(name = "DefaultSubtypeCode")
  protected Integer defaultSubtypeCode;

  @XmlElement(name = "Subtypes")
  protected ArrayOfSubtype subtypes;

  @XmlElement(name = "ControllerMemberships")
  protected ArrayOfControllerMembership controllerMemberships = new ArrayOfControllerMembership();

  /** Gets the value of the hasOID property. */
  public boolean isHasOID() {
    return hasOID;
  }

  /** Sets the value of the hasOID property. */
  public void setHasOID(boolean value) {
    this.hasOID = value;
  }

  /**
   * Gets the value of the oidFieldName property.
   *
   * @return possible object is {@link String }
   */
  public String getOIDFieldName() {
    return oidFieldName;
  }

  /**
   * Sets the value of the oidFieldName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOIDFieldName(String value) {
    this.oidFieldName = value;
  }

  /**
   * Gets the value of the fields property.
   *
   * @return possible object is {@link Fields }
   */
  public Fields getFields() {
    return fields;
  }

  /**
   * Sets the value of the fields property.
   *
   * @param value allowed object is {@link Fields }
   */
  public void setFields(Fields value) {
    this.fields = value;
  }

  /**
   * Gets the value of the indexes property.
   *
   * @return possible object is {@link Indexes }
   */
  public Indexes getIndexes() {
    return indexes;
  }

  /**
   * Sets the value of the indexes property.
   *
   * @param value allowed object is {@link Indexes }
   */
  public void setIndexes(Indexes value) {
    this.indexes = value;
  }

  /**
   * Gets the value of the clsid property.
   *
   * @return possible object is {@link String }
   */
  public String getCLSID() {
    return clsid;
  }

  /**
   * Sets the value of the clsid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCLSID(String value) {
    this.clsid = value;
  }

  /**
   * Gets the value of the extclsid property.
   *
   * @return possible object is {@link String }
   */
  public String getEXTCLSID() {
    return extclsid;
  }

  /**
   * Sets the value of the extclsid property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEXTCLSID(String value) {
    this.extclsid = value;
  }

  /**
   * Gets the value of the relationshipClassNames property.
   *
   * @return possible object is {@link Names }
   */
  public Names getRelationshipClassNames() {
    return relationshipClassNames;
  }

  /**
   * Sets the value of the relationshipClassNames property.
   *
   * @param value allowed object is {@link Names }
   */
  public void setRelationshipClassNames(Names value) {
    this.relationshipClassNames = value;
  }

  /**
   * Gets the value of the aliasName property.
   *
   * @return possible object is {@link String }
   */
  public String getAliasName() {
    return aliasName;
  }

  /**
   * Sets the value of the aliasName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAliasName(String value) {
    this.aliasName = value;
  }

  /**
   * Gets the value of the modelName property.
   *
   * @return possible object is {@link String }
   */
  public String getModelName() {
    return modelName;
  }

  /**
   * Sets the value of the modelName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setModelName(String value) {
    this.modelName = value;
  }

  /**
   * Gets the value of the hasGlobalID property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isHasGlobalID() {
    return hasGlobalID;
  }

  /**
   * Sets the value of the hasGlobalID property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setHasGlobalID(Boolean value) {
    this.hasGlobalID = value;
  }

  /**
   * Gets the value of the globalIDFieldName property.
   *
   * @return possible object is {@link String }
   */
  public String getGlobalIDFieldName() {
    return globalIDFieldName;
  }

  /**
   * Sets the value of the globalIDFieldName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setGlobalIDFieldName(String value) {
    this.globalIDFieldName = value;
  }

  /**
   * Gets the value of the rasterFieldName property.
   *
   * @return possible object is {@link String }
   */
  public String getRasterFieldName() {
    return rasterFieldName;
  }

  /**
   * Sets the value of the rasterFieldName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRasterFieldName(String value) {
    this.rasterFieldName = value;
  }

  /**
   * Gets the value of the extensionProperties property.
   *
   * @return possible object is {@link PropertySet }
   */
  public PropertySet getExtensionProperties() {
    return extensionProperties;
  }

  /**
   * Sets the value of the extensionProperties property.
   *
   * @param value allowed object is {@link PropertySet }
   */
  public void setExtensionProperties(PropertySet value) {
    this.extensionProperties = value;
  }

  /**
   * Gets the value of the subtypeFieldName property.
   *
   * @return possible object is {@link String }
   */
  public String getSubtypeFieldName() {
    return subtypeFieldName;
  }

  /**
   * Sets the value of the subtypeFieldName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubtypeFieldName(String value) {
    this.subtypeFieldName = value;
  }

  /**
   * Gets the value of the defaultSubtypeCode property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getDefaultSubtypeCode() {
    return defaultSubtypeCode;
  }

  /**
   * Sets the value of the defaultSubtypeCode property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setDefaultSubtypeCode(Integer value) {
    this.defaultSubtypeCode = value;
  }

  /**
   * Gets the value of the subtypes property.
   *
   * @return possible object is {@link ArrayOfSubtype }
   */
  public ArrayOfSubtype getSubtypes() {
    return subtypes;
  }

  /**
   * Sets the value of the subtypes property.
   *
   * @param value allowed object is {@link ArrayOfSubtype }
   */
  public void setSubtypes(ArrayOfSubtype value) {
    this.subtypes = value;
  }

  /**
   * Gets the value of the controllerMemberships property.
   *
   * @return possible object is {@link ArrayOfControllerMembership }
   */
  public ArrayOfControllerMembership getControllerMemberships() {
    return controllerMemberships;
  }

  /**
   * Sets the value of the controllerMemberships property.
   *
   * @param value allowed object is {@link ArrayOfControllerMembership }
   */
  public void setControllerMemberships(ArrayOfControllerMembership value) {
    this.controllerMemberships = value;
  }
}
