//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for esriDatasetType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="esriDatasetType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="esriDTAny"/>
 *     &lt;enumeration value="esriDTContainer"/>
 *     &lt;enumeration value="esriDTGeo"/>
 *     &lt;enumeration value="esriDTFeatureDataset"/>
 *     &lt;enumeration value="esriDTFeatureClass"/>
 *     &lt;enumeration value="esriDTPlanarGraph"/>
 *     &lt;enumeration value="esriDTGeometricNetwork"/>
 *     &lt;enumeration value="esriDTText"/>
 *     &lt;enumeration value="esriDTTable"/>
 *     &lt;enumeration value="esriDTRelationshipClass"/>
 *     &lt;enumeration value="esriDTRasterDataset"/>
 *     &lt;enumeration value="esriDTRasterBand"/>
 *     &lt;enumeration value="esriDTTin"/>
 *     &lt;enumeration value="esriDTCadDrawing"/>
 *     &lt;enumeration value="esriDTRasterCatalog"/>
 *     &lt;enumeration value="esriDTTopology"/>
 *     &lt;enumeration value="esriDTToolbox"/>
 *     &lt;enumeration value="esriDTTool"/>
 *     &lt;enumeration value="esriDTNetworkDataset"/>
 *     &lt;enumeration value="esriDTTerrain"/>
 *     &lt;enumeration value="esriDTRepresentationClass"/>
 *     &lt;enumeration value="esriDTCadastralFabric"/>
 *     &lt;enumeration value="esriDTSchematicDataset"/>
 *     &lt;enumeration value="esriDTLocator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "esriDatasetType")
@XmlEnum
public enum EsriDatasetType {

  /** Any Dataset. */
  @XmlEnumValue("esriDTAny")
  ESRI_DT_ANY("esriDTAny"),

  /** Any Container Dataset. */
  @XmlEnumValue("esriDTContainer")
  ESRI_DT_CONTAINER("esriDTContainer"),

  /** Any Geo Dataset. */
  @XmlEnumValue("esriDTGeo")
  ESRI_DT_GEO("esriDTGeo"),

  /** Feature Dataset. */
  @XmlEnumValue("esriDTFeatureDataset")
  ESRI_DT_FEATURE_DATASET("esriDTFeatureDataset"),

  /** Feature Class. */
  @XmlEnumValue("esriDTFeatureClass")
  ESRI_DT_FEATURE_CLASS("esriDTFeatureClass"),

  /** Planar Graph. */
  @XmlEnumValue("esriDTPlanarGraph")
  ESRI_DT_PLANAR_GRAPH("esriDTPlanarGraph"),

  /** Geometric Network. */
  @XmlEnumValue("esriDTGeometricNetwork")
  ESRI_DT_GEOMETRIC_NETWORK("esriDTGeometricNetwork"),

  /** Text Dataset. */
  @XmlEnumValue("esriDTText")
  ESRI_DT_TEXT("esriDTText"),

  /** Table Dataset. */
  @XmlEnumValue("esriDTTable")
  ESRI_DT_TABLE("esriDTTable"),

  /** Relationship Class. */
  @XmlEnumValue("esriDTRelationshipClass")
  ESRI_DT_RELATIONSHIP_CLASS("esriDTRelationshipClass"),

  /** Raster Dataset. */
  @XmlEnumValue("esriDTRasterDataset")
  ESRI_DT_RASTER_DATASET("esriDTRasterDataset"),

  /** Raster Band. */
  @XmlEnumValue("esriDTRasterBand")
  ESRI_DT_RASTER_BAND("esriDTRasterBand"),

  /** Tin Dataset. */
  @XmlEnumValue("esriDTTin")
  ESRI_DT_TIN("esriDTTin"),

  /** CadDrawing Dataset. */
  @XmlEnumValue("esriDTCadDrawing")
  ESRI_DT_CAD_DRAWING("esriDTCadDrawing"),

  /** Raster Catalog. */
  @XmlEnumValue("esriDTRasterCatalog")
  ESRI_DT_RASTER_CATALOG("esriDTRasterCatalog"),

  /** Topology. */
  @XmlEnumValue("esriDTTopology")
  ESRI_DT_TOPOLOGY("esriDTTopology"),

  /** Toolbox. */
  @XmlEnumValue("esriDTToolbox")
  ESRI_DT_TOOLBOX("esriDTToolbox"),

  /** Tool. */
  @XmlEnumValue("esriDTTool")
  ESRI_DT_TOOL("esriDTTool"),

  /** Network Dataset. */
  @XmlEnumValue("esriDTNetworkDataset")
  ESRI_DT_NETWORK_DATASET("esriDTNetworkDataset"),

  /** Terrain dataset. */
  @XmlEnumValue("esriDTTerrain")
  ESRI_DT_TERRAIN("esriDTTerrain"),

  /** Feature Class Representation. */
  @XmlEnumValue("esriDTRepresentationClass")
  ESRI_DT_REPRESENTATION_CLASS("esriDTRepresentationClass"),

  /** Cadastral Fabric. */
  @XmlEnumValue("esriDTCadastralFabric")
  ESRI_DT_CADASTRAL_FABRIC("esriDTCadastralFabric"),

  /** Schematic Dataset. */
  @XmlEnumValue("esriDTSchematicDataset")
  ESRI_DT_SCHEMATIC_DATASET("esriDTSchematicDataset"),

  /** Address Locator. */
  @XmlEnumValue("esriDTLocator")
  ESRI_DT_LOCATOR("esriDTLocator");
  private final String value;

  EsriDatasetType(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static EsriDatasetType fromValue(String v) {
    for (EsriDatasetType c : EsriDatasetType.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
