//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for esriGeometryType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="esriGeometryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="esriGeometryPoint"/>
 *     &lt;enumeration value="esriGeometryMultipoint"/>
 *     &lt;enumeration value="esriGeometryPolyline"/>
 *     &lt;enumeration value="esriGeometryPolygon"/>
 *     &lt;enumeration value="esriGeometryMultiPatch"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "esriGeometryType")
@XmlEnum
public enum EsriGeometryType {
  @XmlEnumValue("esriGeometryPoint")
  ESRI_GEOMETRY_POINT("esriGeometryPoint"),
  @XmlEnumValue("esriGeometryMultipoint")
  ESRI_GEOMETRY_MULTIPOINT("esriGeometryMultipoint"),
  @XmlEnumValue("esriGeometryPolyline")
  ESRI_GEOMETRY_POLYLINE("esriGeometryPolyline"),
  @XmlEnumValue("esriGeometryPolygon")
  ESRI_GEOMETRY_POLYGON("esriGeometryPolygon"),
  @XmlEnumValue("esriGeometryMultiPatch")
  ESRI_GEOMETRY_MULTI_PATCH("esriGeometryMultiPatch");
  private final String value;

  EsriGeometryType(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static EsriGeometryType fromValue(String v) {
    for (EsriGeometryType c : EsriGeometryType.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
