//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for esriNetworkClassAncillaryRole.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="esriNetworkClassAncillaryRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="esriNCARNone"/>
 *     &lt;enumeration value="esriNCARSourceSink"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "esriNetworkClassAncillaryRole")
@XmlEnum
public enum EsriNetworkClassAncillaryRole {

  /** No ancillary role. */
  @XmlEnumValue("esriNCARNone")
  ESRI_NCAR_NONE("esriNCARNone"),

  /** Source Sink ancillary role. */
  @XmlEnumValue("esriNCARSourceSink")
  ESRI_NCAR_SOURCE_SINK("esriNCARSourceSink");
  private final String value;

  EsriNetworkClassAncillaryRole(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static EsriNetworkClassAncillaryRole fromValue(String v) {
    for (EsriNetworkClassAncillaryRole c : EsriNetworkClassAncillaryRole.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
