//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * ESRI Fields Object.
 *
 * <p>Java class for Fields complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Fields">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldArray" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfField"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "Fields",
  propOrder = {"fieldArray"}
)
public class Fields {

  @XmlElement(name = "FieldArray", required = true)
  protected ArrayOfField fieldArray;

  /**
   * Gets the value of the fieldArray property.
   *
   * @return possible object is {@link ArrayOfField }
   */
  public ArrayOfField getFieldArray() {
    return fieldArray;
  }

  /**
   * Sets the value of the fieldArray property.
   *
   * @param value allowed object is {@link ArrayOfField }
   */
  public void setFieldArray(ArrayOfField value) {
    this.fieldArray = value;
  }
}
