//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.21 at 09:16:28 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esri.com/schemas/ArcGIS/10.1")
package org.fgdbapi.thindriver.xml;
