//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * ESRI Range Domain object.
 *
 * <p>Java class for RangeDomain complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RangeDomain">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.esri.com/schemas/ArcGIS/10.1}Domain">
 *       &lt;sequence>
 *         &lt;element name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="MinValue" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "RangeDomain",
  propOrder = {"maxValue", "minValue"}
)
public class RangeDomain extends Domain {

  @XmlElement(name = "MaxValue", required = true)
  protected Object maxValue;

  @XmlElement(name = "MinValue", required = true)
  protected Object minValue;

  /**
   * Gets the value of the maxValue property.
   *
   * @return possible object is {@link Object }
   */
  public Object getMaxValue() {
    return maxValue;
  }

  /**
   * Sets the value of the maxValue property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setMaxValue(Object value) {
    this.maxValue = value;
  }

  /**
   * Gets the value of the minValue property.
   *
   * @return possible object is {@link Object }
   */
  public Object getMinValue() {
    return minValue;
  }

  /**
   * Sets the value of the minValue property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setMinValue(Object value) {
    this.minValue = value;
  }
}
