//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Raster Column Definition Class.
 *
 * <p>Java class for RasterDef complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RasterDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsByRef" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SpatialReference" type="{http://www.esri.com/schemas/ArcGIS/10.1}SpatialReference" minOccurs="0"/>
 *         &lt;element name="IsByFunction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "RasterDef",
  propOrder = {"description", "isByRef", "spatialReference", "isByFunction"}
)
public class RasterDef {

  @XmlElement(name = "Description")
  protected String description;

  @XmlElement(name = "IsByRef")
  protected Boolean isByRef;

  @XmlElement(name = "SpatialReference")
  protected SpatialReference spatialReference;

  @XmlElement(name = "IsByFunction")
  protected Boolean isByFunction;

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the isByRef property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsByRef() {
    return isByRef;
  }

  /**
   * Sets the value of the isByRef property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsByRef(Boolean value) {
    this.isByRef = value;
  }

  /**
   * Gets the value of the spatialReference property.
   *
   * @return possible object is {@link SpatialReference }
   */
  public SpatialReference getSpatialReference() {
    return spatialReference;
  }

  /**
   * Sets the value of the spatialReference property.
   *
   * @param value allowed object is {@link SpatialReference }
   */
  public void setSpatialReference(SpatialReference value) {
    this.spatialReference = value;
  }

  /**
   * Gets the value of the isByFunction property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsByFunction() {
    return isByFunction;
  }

  /**
   * Sets the value of the isByFunction property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsByFunction(Boolean value) {
    this.isByFunction = value;
  }
}
