//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.21 at 09:16:28 AM CEST
//

package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for SubtypeFieldInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubtypeFieldInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DomainName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
  name = "SubtypeFieldInfo",
  propOrder = {"fieldName", "domainName", "defaultValue"}
)
public class SubtypeFieldInfo {

  @XmlElement(name = "FieldName", required = true)
  protected String fieldName;

  @XmlElement(name = "DomainName")
  protected String domainName;

  @XmlElement(name = "DefaultValue")
  protected Object defaultValue;

  /**
   * Gets the value of the fieldName property.
   *
   * @return possible object is {@link String }
   */
  public String getFieldName() {
    return fieldName;
  }

  /**
   * Sets the value of the fieldName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFieldName(String value) {
    this.fieldName = value;
  }

  /**
   * Gets the value of the domainName property.
   *
   * @return possible object is {@link String }
   */
  public String getDomainName() {
    return domainName;
  }

  /**
   * Sets the value of the domainName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDomainName(String value) {
    this.domainName = value;
  }

  /**
   * Gets the value of the defaultValue property.
   *
   * @return possible object is {@link Object }
   */
  public Object getDefaultValue() {
    return defaultValue;
  }

  /**
   * Sets the value of the defaultValue property.
   *
   * @param value allowed object is {@link Object }
   */
  public void setDefaultValue(Object value) {
    this.defaultValue = value;
  }
}
