//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.21 at 09:16:28 AM CEST 
//


package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The (GP) Subtype Object.
 * 
 * <p>Java class for Subtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubtypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubtypeCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FieldInfos" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfSubtypeFieldInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subtype", propOrder = {
    "subtypeName",
    "subtypeCode",
    "fieldInfos"
})
public class Subtype {

    @XmlElement(name = "SubtypeName", required = true)
    protected String subtypeName;
    @XmlElement(name = "SubtypeCode")
    protected int subtypeCode;
    @XmlElement(name = "FieldInfos", required = true)
    protected ArrayOfSubtypeFieldInfo fieldInfos;

    /**
     * Gets the value of the subtypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtypeName() {
        return subtypeName;
    }

    /**
     * Sets the value of the subtypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtypeName(String value) {
        this.subtypeName = value;
    }

    /**
     * Gets the value of the subtypeCode property.
     * 
     */
    public int getSubtypeCode() {
        return subtypeCode;
    }

    /**
     * Sets the value of the subtypeCode property.
     * 
     */
    public void setSubtypeCode(int value) {
        this.subtypeCode = value;
    }

    /**
     * Gets the value of the fieldInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSubtypeFieldInfo }
     *     
     */
    public ArrayOfSubtypeFieldInfo getFieldInfos() {
        return fieldInfos;
    }

    /**
     * Sets the value of the fieldInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSubtypeFieldInfo }
     *     
     */
    public void setFieldInfos(ArrayOfSubtypeFieldInfo value) {
        this.fieldInfos = value;
    }

}
