/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class IndexDef {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IndexDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_IndexDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexDef() {
    this(FGDBJNIWrapperJNI.new_IndexDef__SWIG_0(), true);
  }

  public IndexDef(String name, String fields, boolean isUnique) {
    this(FGDBJNIWrapperJNI.new_IndexDef__SWIG_1(name, fields, isUnique), true);
  }

  public IndexDef(String name, String fields) {
    this(FGDBJNIWrapperJNI.new_IndexDef__SWIG_2(name, fields), true);
  }

  public int SetName(String name) {
    return FGDBJNIWrapperJNI.IndexDef_SetName(swigCPtr, this, name);
  }

  public int SetFields(String fields) {
    return FGDBJNIWrapperJNI.IndexDef_SetFields(swigCPtr, this, fields);
  }

  public int SetIsUnique(boolean isUnique) {
    return FGDBJNIWrapperJNI.IndexDef_SetIsUnique(swigCPtr, this, isUnique);
  }

  public boolean isUnique() {
    return FGDBJNIWrapperJNI.IndexDef_isUnique(swigCPtr, this);
  }

  public String getName() {
    return FGDBJNIWrapperJNI.IndexDef_getName(swigCPtr, this);
  }

  public String getFields() {
    return FGDBJNIWrapperJNI.IndexDef_getFields(swigCPtr, this);
  }

}
