/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fgdbapi.thindriver.swig;

public class VectorOfFieldDef {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorOfFieldDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfFieldDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FGDBJNIWrapperJNI.delete_VectorOfFieldDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfFieldDef() {
    this(FGDBJNIWrapperJNI.new_VectorOfFieldDef__SWIG_0(), true);
  }

  public VectorOfFieldDef(long n) {
    this(FGDBJNIWrapperJNI.new_VectorOfFieldDef__SWIG_1(n), true);
  }

  public long size() {
    return FGDBJNIWrapperJNI.VectorOfFieldDef_size(swigCPtr, this);
  }

  public long capacity() {
    return FGDBJNIWrapperJNI.VectorOfFieldDef_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    FGDBJNIWrapperJNI.VectorOfFieldDef_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return FGDBJNIWrapperJNI.VectorOfFieldDef_isEmpty(swigCPtr, this);
  }

  public void clear() {
    FGDBJNIWrapperJNI.VectorOfFieldDef_clear(swigCPtr, this);
  }

  public void add(FieldDef x) {
    FGDBJNIWrapperJNI.VectorOfFieldDef_add(swigCPtr, this, FieldDef.getCPtr(x), x);
  }

  public FieldDef get(int i) {
    return new FieldDef(FGDBJNIWrapperJNI.VectorOfFieldDef_get(swigCPtr, this, i), false);
  }

  public void set(int i, FieldDef val) {
    FGDBJNIWrapperJNI.VectorOfFieldDef_set(swigCPtr, this, i, FieldDef.getCPtr(val), val);
  }

}
