//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.21 at 09:16:28 AM CEST 
//


package org.fgdbapi.thindriver.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ESRI Indices Object.
 * 
 * <p>Java class for Indexes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Indexes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndexArray" type="{http://www.esri.com/schemas/ArcGIS/10.1}ArrayOfIndex"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Indexes", propOrder = {
    "indexArray"
})
public class Indexes {

    @XmlElement(name = "IndexArray", required = true)
    protected ArrayOfIndex indexArray;

    /**
     * Gets the value of the indexArray property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfIndex }
     *     
     */
    public ArrayOfIndex getIndexArray() {
        return indexArray;
    }

    /**
     * Sets the value of the indexArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfIndex }
     *     
     */
    public void setIndexArray(ArrayOfIndex value) {
        this.indexArray = value;
    }

}
